version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename:-Zero-G-chat}:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: zerogchat

volumes:
  postgres-data:
